#spring.jpa.hibernate.ddl-auto= none
#spring.datasource.url=jdbc:postgresql://priorpostgres.cmbcolowaua6.ap-southeast-1.rds.amazonaws.com:5432/PR
#spring.datasource.url=jdbc:postgresql://localhost:5432/KK
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#spring.datasource.username=prioradmin
#spring.datasource.password=prioradminpassword
#spring.datasource.username=postgres
#spring.datasource.password=123456789
#server.servlet.context-path=/kk


server:
  port: 8443
  compression:
    enabled: true
    min-response-size: 1KB
  http2:
    enabled: true
  tomcat:
    accesslog:
      enabled: true
      directory: src/main/resources/tomcat-log
      pattern: '%t %I %r %s %b %D'

  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/kamonkit.p12
    key-store-password: na2i1l6j
    key-alias: kamonkit
    

spring:
  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      hibernate.generate_statistics: false

    open-in-view: false

  datasource:
    url: jdbc:postgresql://localhost:5432/KK
    username: postgres
    password: 123456789


